### ISSUE TITLE
Rigid and Soft - would you consider adding them to the vibration pattern symbols? Thanks!

### ISSUE THREAD

**Issue by chrisperfer** [efremidze/Haptic#23]
### New Issue Checklist

- [x ] I updated Haptica to the latest version.
- [x ] I read the [Contribution Guidelines](https://github.com/efremidze/Haptica/blob/master/.github/CONTRIBUTING.md).
- [x ] I read the [documentation](https://github.com/efremidze/Haptica).
- [x ] I searched for [existing GitHub issues](https://github.com/efremidze/Haptica/issues).

### Issue Description

Title says it all.

Thanks!
### Environment

- **iOS Version**: [any]
- **Device(s)**: [any]

**Comment by efremidze** [comment]
Shipped in Haptica v3.0.3
https://github.com/efremidze/Haptica/releases/tag/3.0.3
