### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by ghost** [efremidze/Haptic#9]
Update to 4.2 please.

**Comment by efremidze** [comment]
I've added Swift 4.2 support
https://github.com/efremidze/Haptica/tree/swift-4.2

**Comment by gintechsystems** [comment]
When will this be merged into master?

**Comment by efremidze** [comment]
I'll merge it asap. Just reviewing some potential issues with backwards compatiblilty.

**Comment by gintechsystems** [comment]
@efremidze I understand, thank you for the work effort!
